
services:
  phpshare:
    build:
      context: .
    volumes:
      - .:/var/www/html
    ports:
      - 8000:8000
    image: phpshare
    environment:
      passwd: ${RANDOM_PASS:-$(openssl rand -base64 12)}
